---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "admin-config"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "admin"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  NODE_ENV: "{{ .Values.config.admin.NODE_ENV }}"
  APIGATEWAY_HTTP: "{{ .Values.config.admin.APIGATEWAY_HTTP }}"
  services__apigateway__http__0: "{{ .Values.config.admin.services__apigateway__http__0 }}"
  BROWSER: "{{ .Values.config.admin.BROWSER }}"
  PORT: "{{ .Values.config.admin.PORT }}"
