---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-config"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  NODE_ENV: "{{ .Values.config.app.NODE_ENV }}"
  APIGATEWAY_HTTP: "{{ .Values.config.app.APIGATEWAY_HTTP }}"
  services__apigateway__http__0: "{{ .Values.config.app.services__apigateway__http__0 }}"
  BROWSER: "{{ .Values.config.app.BROWSER }}"
  PORT: "{{ .Values.config.app.PORT }}"
