---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "app-deployment"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "platform-apphost"
        app.kubernetes.io/component: "app"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.app.app_image }}"
          name: "app"
          envFrom:
            - configMapRef:
                name: "app-config"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8081
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "platform-apphost"
      app.kubernetes.io/component: "app"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
