---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "datainitializer-config"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "datainitializer"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "{{ .Values.config.datainitializer.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.datainitializer.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.datainitializer.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.datainitializer.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.datainitializer.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.datainitializer.HTTP_PORTS }}"
  MONGODB_HOST: "{{ .Values.config.datainitializer.MONGODB_HOST }}"
  MONGODB_PORT: "{{ .Values.config.datainitializer.MONGODB_PORT }}"
  MONGODB_USERNAME: "{{ .Values.config.datainitializer.MONGODB_USERNAME }}"
  MONGODB_AUTHENTICATIONDATABASE: "{{ .Values.config.datainitializer.MONGODB_AUTHENTICATIONDATABASE }}"
  MONGODB_AUTHENTICATIONMECHANISM: "{{ .Values.config.datainitializer.MONGODB_AUTHENTICATIONMECHANISM }}"
  MONGODB_DATABASE: "{{ .Values.config.datainitializer.MONGODB_DATABASE }}"
