---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mongo-config"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "mongo"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  MONGO_INITDB_ROOT_USERNAME: "{{ .Values.config.mongo.MONGO_INITDB_ROOT_USERNAME }}"
