---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "apiservice-config"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "apiservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "{{ .Values.config.apiservice.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.apiservice.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.apiservice.HTTP_PORTS }}"
  MONGODB_HOST: "{{ .Values.config.apiservice.MONGODB_HOST }}"
  MONGODB_PORT: "{{ .Values.config.apiservice.MONGODB_PORT }}"
  MONGODB_USERNAME: "{{ .Values.config.apiservice.MONGODB_USERNAME }}"
  MONGODB_AUTHENTICATIONDATABASE: "{{ .Values.config.apiservice.MONGODB_AUTHENTICATIONDATABASE }}"
  MONGODB_AUTHENTICATIONMECHANISM: "{{ .Values.config.apiservice.MONGODB_AUTHENTICATIONMECHANISM }}"
  MONGODB_DATABASE: "{{ .Values.config.apiservice.MONGODB_DATABASE }}"
  Jwt__SecretKey: "{{ .Values.config.apiservice.Jwt__SecretKey }}"
  CHAT_ENDPOINT: "{{ .Values.config.apiservice.CHAT_ENDPOINT }}"
  CHAT_URI: "{{ .Values.config.apiservice.CHAT_URI }}"
  CHAT_MODEL: "{{ .Values.config.apiservice.CHAT_MODEL }}"
