---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "apigateway-deployment"
  labels:
    app.kubernetes.io/name: "platform-apphost"
    app.kubernetes.io/component: "apigateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "platform-apphost"
        app.kubernetes.io/component: "apigateway"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - command:
            - "dotnet"
          image: "mcr.microsoft.com/dotnet/nightly/yarp:2.3.0-preview.4"
          name: "apigateway"
          envFrom:
            - configMapRef:
                name: "apigateway-config"
          args:
            - "/app/yarp.dll"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 5000
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "platform-apphost"
      app.kubernetes.io/component: "apigateway"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
